---
driver:
  name: vagrant
driver_config:
  require_chef_omnibus: true
  use_vagrant_berkshelf_plugin: true
  customize:
    memory: 2048
    cpus: 2

provisioner:
  name: chef_solo

platforms:
  - name: windows
    driver:
      name: vagrant_provision
    driver_config:
      box: windows2012-chef
      box_url: box\windows2012-chef.box
      vagrantfile_erb: 'Vagrantfile.windows.erb' 

suites:
  - name: default
    run_list:
      - recipe[sql_server::default]
    attributes: